name: Envio dos Clippings

on:
  schedule:
    - cron: '0 11 * * *' # 8h no horario de Brasilia
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Clonar o repositório
        uses: actions/checkout@v3

      - name: 🐍 Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: 📦 Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install scrapy python-dateutil dateparser text-unidecode thefuzz filetype pymupdf pyyamlL

      - name: 🚀 Executar script
        run: python gerar_enviar_clipping.py
        env:
          EMAIL_REMETENTE: ${{ secrets.EMAIL_REMETENTE }}
          EMAIL_SENHA: ${{ secrets.EMAIL_SENHA }}
          DESTINATARIOS_ADESOES_ARP: ${{ vars.DESTINATARIOS_ADESOES_ARP }}
          DESTINATARIOS_CAD_EDUCACAO: ${{ vars.DESTINATARIOS_CAD_EDUCACAO }}
          DESTINATARIOS_CAD_SEGURANCA: ${{ vars.DESTINATARIOS_CAD_SEGURANCA }}
          DESTINATARIOS_CAD_TI: ${{ vars.DESTINATARIOS_CAD_TI }}
