name: Envio dos Clippings

on:
  schedule:
    - cron: '0 11 * * *' # 8h no horario de Brasilia
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Clonar o repositório
        uses: actions/checkout@v3

      - name: 📥 Instalar GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh

      - name: 📥 Baixar artefato ultima-edicao mais recente
        run: |
          # Pega o run_id mais recente do workflow "Envio dos Clippings"
          RUN_ID=$(gh run list --workflow "Envio dos Clippings" --json databaseId --jq '.[0].databaseId' || echo "")

          if [ -n "$RUN_ID" ]; then
            echo "Baixando artefato da execução: $RUN_ID"
            gh run download $RUN_ID --name ultima-edicao --dir .
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true  # não falha se não existir ainda

      - name: 🐍 Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: 📦 Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install scrapy python-dateutil dateparser text-unidecode thefuzz filetype pymupdf pyyaml

      - name: 🚀 Executar script
        run: python baixar_diarios_enviar_clipping.py
        env:
          EMAIL_REMETENTE: ${{ secrets.EMAIL_REMETENTE }}
          EMAIL_SENHA: ${{ secrets.EMAIL_SENHA }}
          DESTINATARIOS_ADESOES_ARP: ${{ vars.DESTINATARIOS_ADESOES_ARP }}
          DESTINATARIOS_CAD_EDUCACAO: ${{ vars.DESTINATARIOS_CAD_EDUCACAO }}
          DESTINATARIOS_CAD_SEGURANCA: ${{ vars.DESTINATARIOS_CAD_SEGURANCA }}
          DESTINATARIOS_CAD_TI: ${{ vars.DESTINATARIOS_CAD_TI }}

      - name: 📤 Enviar artefato ultima-edicao atualizado
        uses: actions/upload-artifact@v4
        with:
          name: ultima-edicao
          path: ultima_edicao.json
